[package]
name = "vertree"
version = "0.1.0"
authors = ["Justin Sheehy <justin@iago.org",
           "Andrew J. Stone <andrew.j.stone.1@gmail.com>"]

[dependencies]
error-chain = "0.5"
serde = "0.8"
serde_derive = "0.8"

[dev-dependencies]
assert_matches = "1.0"
